# Generated by Django 3.2.8 on 2021-12-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211108_0137'),
        ('home', '0006_auto_20211109_0948'),
    ]

    operations = [
    ]
